### ISSUE TITLE
Cut.pop(key, default) raises KeyError when key doesn't exist.

### ISSUE THREAD

**Issue by gilabrantes** [ducdetronquito/scalpl#11]
When default is given, Cut.pop(key, default) is expected to return default if key doesn't exist.

Reproducing steps:
```
>>> from scalpl import Cut
>>> a = Cut()
>>> a.pop('give.me.key', False)
(...)
line 229, in _traverse
    raise key_error(sub_key, path, error)
KeyError: "Cannot access key 'give' in path 'give.me.key', because of error: KeyError('give',)."
```

**Comment by ducdetronquito** [comment]
Hello @gilabrantes !

Thank you for reporting this bug with clear reproducing steps :)
It's actually really helpful as it made me discover some other bugs.

Depending on the amount of changes required, I will release either a bugfix version (0.3.2) or a feature version (0.4.0) before the end of the week.

I keep you in touch.

Have a nice day 🌴

**Comment by gilabrantes** [comment]
Hello!

No problem and thank you for your quick response. - I'll keep an eye out for the new relase.

Keep up the good work! :)

**Comment by gilabrantes** [comment]
Hello!
Do you have an ETA for the further fixes and following release?

**Comment by ducdetronquito** [comment]
Hello @gilabrantes !

Sorry for the delay, instead of just making a bugfix release I spent time on building a 0.4.0 which should be ready by the end of the week (again).

This release will:
 
- Fix this bug and some others
- Improve debugging

I will keep you in touch !

**Comment by ducdetronquito** [comment]
Hey @gilabrantes !

Sorry for being extra late on this issue.
Like I mentionned in the issue https://github.com/ducdetronquito/scalpl/issues/16 I reworked scalpl's codebase a lot to fix many bugs found since september.

The version 0.4.0 is not release yet on PyPI, as I want to be sure that no bugs are left.

If you have the time, could you please confirm me that you do not encounter the bug on the master branch ?

```python
from scalpl import Cut

proxy = Cut()
assert proxy.pop('give.me.key', False) is False
```

Thank you in advance and have a nice day 🌴

**Comment by ducdetronquito** [comment]
Hey @gilabrantes,
The version 0.4.0 of scalpl has just been released: you will not be bothered by this bug anymore !

**Comment by gilabrantes** [comment]
Understood, thank you for the fix!
