### ISSUE TITLE
Cut.get(foo, default=None) with diverges from dict API

### ISSUE THREAD

**Issue by gimbo** [ducdetronquito/scalpl#16]
`README.rst` says:

> This wrapper strictly follows the standard dict API, 

However, scalpl diverges from that API in the case of `get` with a default of `None`; dicts return `None` in that case, whereas `scalpl` raises `KeyError`:

```
>>> {}.get('a', None) is None
True
```

vs

```
>>> from scalpl import Cut
>>> Cut({}).get('a', None)
Traceback (most recent call last):
  File "/Users/gimbo/.virtualenvs/cloudiest-py3.7/lib/python3.7/site-packages/scalpl/scalpl.py", line 83, in __getitem__
    return parent[last_key]
KeyError: 'a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gimbo/.virtualenvs/cloudiest-py3.7/lib/python3.7/site-packages/scalpl/scalpl.py", line 133, in get
    raise error
  File "/Users/gimbo/.virtualenvs/cloudiest-py3.7/lib/python3.7/site-packages/scalpl/scalpl.py", line 129, in get
    return self[path]
  File "/Users/gimbo/.virtualenvs/cloudiest-py3.7/lib/python3.7/site-packages/scalpl/scalpl.py", line 85, in __getitem__
    raise key_error(last_key, path, error)
KeyError: "Cannot access key 'a' in path 'a', because of error: KeyError('a')."
```

This is arising because `Cut.get()` is using `None` as a sentinel to represent "no default".

A possible fix would be to change its type signature so that instead of receiving `default: Optional[Any] = None`, it receives `**kwargs` and explicitly looks for the presence/absence of `default` there; the downside is you lose some type information (and would, strictly, also need to explicitly exclude all kwargs other than `default`).

**Comment by gimbo** [comment]
Of course, that "possible fix" insists that `default` is specified as a kwarg not an ordinary arg; it can be done both ways but it's more complex...

**Comment by gimbo** [comment]
In case this helps anybody, this is how I worked around it; the context is an ansible filter, but it should be easily adaptable to other situations, including a fix for `scapl.Cut.get()` of course. It's fairly verbose, there's probably a simpler way to do it, but hopefully it's clear...

```
from contextlib import suppress
import uuid

import scalpl

class SomeClass:

    def deep_get(self, target, path, *args, **kwargs):
        """Deep get via scalpl

        SomeClass().deep_get({'a': {'b': {'c': 3, 'd': 4}}}, 'a.b.c')
        # Result: 3

        SomeClass().deep_get({'a': {'b': {'c': 3, 'd': 4}}}, 'a.b.e')
        # Result: KeyError

        SomeClass().deep_get({'a': {'b': {'c': 3, 'd': 4}}}, 'a.b.e', None)
        # Result: None

        SomeClass().deep_get({'a': {'b': {'c': 3, 'd': 4}}}, 'a.b.e', default=None)
        # Result: None
        """

        # Some slightly verbose logic here to emulate how `dict.get()`
        # behaves: `None` should be a possible default value (rather
        # than a sentinel indicating 'no default value', as is
        # currently the case in `scalpl.Cut.get()` - see
        # https://github.com/ducdetronquito/scalpl/issues/16)

        # Fundamentally, we build a dict to pass as **kwargs to
        # `scalpl.Cut.get()` - it will either be empty or contain one
        # key, which will be 'default'.
        inner_kwargs = {}

        # First, look for default value as a positional argument.
        default_as_positional = len(args) == 1
        if default_as_positional:
            inner_kwargs['default'] = args[0]
        # (And ensure there are no other positional arguments.)
        if len(args) > 1:
            raise TypeError(
                (
                    'deep_get takes at most 3 positional arguments but '
                    '{} were given'.format(len(args) + 2)
                )
            )

        # Next, look for default value as a keyword argument.
        default_as_keyword = 'default' in kwargs
        if default_as_keyword:
            inner_kwargs['default'] = kwargs.pop('default')
        # (And ensure there are no other keyword arguments.)
        if kwargs:
            raise TypeError('deep_get received unexpected kwargs', kwargs)

        # Check for default value as both positional and keyword
        # arguments (naughty).
        if default_as_positional and default_as_keyword:
            raise TypeError(
                (
                    'deep_get received default value both as '
                    'positional and keyword argument'
                )
            )

        # Finally, if we have a default value of `None`, don't pass it
        # through to `scalpl.Cut.get()`; instead, pass a random
        # sentinel value, and if that's returned, translate it back to
        # `None`.

        sentinel = None
        with suppress(KeyError):
            if inner_kwargs['default'] is None:
                inner_kwargs['default'] = sentinel = uuid4()

        proxy = scalpl.Cut(target)
        result = proxy.get(path, **inner_kwargs)

        if sentinel is not None and result == sentinel:
            result = None

        return result
```

**Comment by ducdetronquito** [comment]
Hi @gimbo !

Thank you very much for this detailed issue, it will really help. I will spare time during christmas and the new year to deal with it and hopefully make a release soon !

Have a nice day, I keep you in touch ✋ ✋

**Comment by gimbo** [comment]
Nice one. :-) 👍

**Comment by chris-noverde** [comment]
Suggestion on `Cut.get` and `Cut.pop`: 
```python
class FakeNone:
   pass

class Cut:
   def get(self, path: str, default: Optional[Any] = FakeNone) -> Any:
        try:
            return self[path]
        except (KeyError, IndexError) as error:
            if default is not FakeNone:
                return default
            raise error
   def pop(self, path: str, default: Any = FakeNone) -> Any:
        parent, last_key = self._traverse(self.data, path)
        try:
            return parent.pop(last_key)
        except IndexError as error:
            if default is not FakeNone:
                return default
            raise index_error(last_key, path, error)
        except (AttributeError, KeyError) as error:
            if default is not FakeNone:
                return default
            raise key_error(last_key, path, error)
```

**Comment by gimbo** [comment]
@chris-noverde That is neat, clever, and way more comprehensible than what I came up with! :-)

**Comment by ducdetronquito** [comment]
Good morning both of you !

The version 0.4.0 of Scalpl that fixes this bug (and improves error handling in general) was pushed into the master branch in January, but I just forgot to push the version on PyPI !

Thanks for your suggestion @chris-noverde, I appreciate it :)
I will have a deeper look at it at the end of the day and I will finally push the 0.4.0 release to PyPI in the upcoming days since I have time to kill (thanks to the quarantine in France) :)

If it is not too much to ask, @gimbo and @chris-noverde : do you still encounter the bug on the master branch ?

The codebase has changed quiet a lot, let me know if you see other room for improvements !

Have a nice day 🌻

**Comment by chris-noverde** [comment]
Hi, thanks for response. Yes, error still occurs after last commit. Hope it helps!

**Comment by ducdetronquito** [comment]
Hi @chris-noverde !

I was unable to reproduce this bug on the master branch, so I just pushed a commit that adds unit tests to ensure it.

On the master branch, you must be able to use the following snippet:
```python
from scalpl import Cut

assert Cut({}).get("a", None) is None
assert Cut({}).get("a", default=None) is None # As a keyword parameter
assert Cut({}).pop("a", None) is None # Keyword parameter is not available in the standard API for .pop
assert Cut({}).setdefault("a", default=None) is None
assert Cut({}).setdefault("a", None) is None
```

This behavior is now unit-tested:
- For `Cut.get`: [here](https://github.com/ducdetronquito/scalpl/blob/96735ee8890f7579921bef82a7b34cc11ce7e6a7/tests/tests.py#L333)
- For `Cut.pop`: [here](https://github.com/ducdetronquito/scalpl/blob/96735ee8890f7579921bef82a7b34cc11ce7e6a7/tests/tests.py#L437)
- For `Cut.setdefault` [here](https://github.com/ducdetronquito/scalpl/blob/96735ee8890f7579921bef82a7b34cc11ce7e6a7/tests/tests.py#L566)

The build passes on Travis for Python 3.6, 3.7 and 3.8 --> [build](https://travis-ci.org/github/ducdetronquito/scalpl/builds/666677846?utm_medium=notification&utm_source=github_status).

If you still encounter an erroneous behavior, could you please show me a snippet of code and the stack-trace of the error ?

Thanks in advance and have a nice day 🌴

**Comment by jakezatecky** [comment]
I can verify that the changes in the master branch fix the error for me.

**Comment by ducdetronquito** [comment]
Thanks for the feedback @jakezatecky !
I will then push the 0.4.0 release on PyPI today :)

**Comment by ducdetronquito** [comment]
The version 0.4.0 of scalpl has just been released: you will not be bothered by this bug anymore ! 🌴

Thanks everyone for your help :)
