### ISSUE TITLE
Charmap Issue

### ISSUE THREAD

**Issue by pandeyarpit88** [ducdetronquito/scalpl#2]
Python 3.6
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 8609: character maps to <undefined>
Define encoding in code to avoid taking other encoding

**Comment by ducdetronquito** [comment]
Hi @pandeyarpit88 !

Thanks for using Scalpl and opening an issue :)

Would you mind to share me a small snippet of code that shows this error ?

**Comment by jsve** [comment]
I get the same problem when trying to pip install this on windows machine. Complete error message below.

```
D:\home\python364x86\python.exe -m pip install scalpl
Collecting scalpl
  Downloading https://files.pythonhosted.org/packages/b0/a9/cff0ada8a2b6eb794eaf92faffd9a4fb2286845f7cb4d9bcc971b77f4efa/scalpl-0.2.5.tar.gz
    Complete output from command python setup.py egg_info:Command "python setup.py egg_info" failed with error code 1 in D:\local\Temp\pip-install-w7h4fqe5\scalpl\
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\local\Temp\pip-install-w7h4fqe5\scalpl\setup.py", line 4, in <module>
        readme = f.read()
      File "E:\A\_work\79\b\source_packages\pythonx86.3.6.4\tools\Lib\encodings\cp1252.py", line 23, in decode
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 8609: character maps to <undefined>
    
    ----------------------------------------

```

**Comment by ducdetronquito** [comment]
Hello @jsve !

Thank you for submitting a detailed stack trace, I will fix it as soon as possible (tomorrow hopefully).

I keep you up to date :)

**Comment by ducdetronquito** [comment]
Hi @jsve and @pandeyarpit88 !

It appeared that the issue was caused because of the default encoding on windows is not UTF-8.
Therefore, the README file could not be read during the installation step.

It's been fixed by the following pull request: https://github.com/ducdetronquito/scalpl/pull/3

I will make a bugfix release on PyPI tonight or tomorrow :)

**Comment by ducdetronquito** [comment]
A minor version 0.2.6 has just been released to fix this issue, and it's available on [Pypi](https://pypi.org/manage/project/scalpl/release/0.2.6/) !

Thank you for your contribution :)
