### ISSUE TITLE
Initialising a proxy from an empty dict.

### ISSUE THREAD

**Issue by runtugen** [ducdetronquito/scalpl#24]
Hi,

I'm getting the following behaviour:
a = {}
proxy = Cut(a)
a is proxy.data # returns False

b = {'test': 1}
proxy = Cut(b)
b is proxy.data # returns True

This is correct behaviour since the dunder-init does:
    def __init__(self, data: Optional[dict] = None, sep: str = ".") -> None:
        self.data = data or {}
 
Since the data parameter is an empty dict, I understand the Python behaviour is to evaluate bool(data) as False since it has a __len__() method that returns 0 (https://docs.python.org/3/library/stdtypes.html#truth-value-testing). Thus the behaviour is correct. 

However, my use case (passing a reference to a potentially empty dict to Cut) caught me by surprise. For example: in a method that receives a dictionary object, I need to use a Cut for accessing/setting deep nested keys in a simple way (for which scalpl is perfect). However since the dict object may be empty, when wrapping the Cut around it, I won't be modifying the original object I'm passing to Cut, I'll be modifying a different object.

Since the data parameter is hinted as Optional, would an explicit check for a None not be preferable? I.e.:

    def __init__(self, data: Optional[dict] = None, sep: str = ".") -> None:
        self.data = {} if data is None else data

Cheerio!

**Comment by ducdetronquito** [comment]
Hi @runtugen,

Wow, good catch ! Using the pattern `value or default_value` is an old habit of mine, but you're right that in this case it caused a bug !

I just released a bugfix version 0.4.2 on PyPI, let me hear if it works for you !

Have a nice sunday :)

**Comment by runtugen** [comment]
Hi @ducdetronquito,

Thanks for the fix! Works perfectly.

Cheerio!
