### ISSUE TITLE
There is a issue with wrapping json-data

### ISSUE THREAD

**Issue by landeholt** [ducdetronquito/scalpl#26]
JSON data can be list of objects as well as objects!

Meaning that when JSON data is a list of objects (dicts), scalpl can not longer traverse it correctly.

test:

```python
from scalpl import Cut
import json

raw_data = "[{\"id\":0}, {\"id\": 2}]"
data = json.loads(raw_data)
proxy = Cut(data)
proxy[0]
>> AttributeError: 'int' object has no attribute 'split'
```

**Comment by ducdetronquito** [comment]
Hi @landeholt ,

It took me some time to think about your issue and the PR you https://github.com/ducdetronquito/scalpl/pull/27.

Scalpl is made to be only syntactic sugar on top of the standard `dict` API: that's what makes its implementation simple and a keep it away from feature creep.

If you want to deal with a list of `dict`, I would simply suggest to deal with it in your codebase with something like this:

```python
if isinstance(data, list):
     cuts = [Cut(item) for item in data]
```

Another option would be to build your own library dedicated to manipulating JSON better and I would be glad if you use Scalpl under the hood :)

I hope you understand and I wish you a nice day !
