### ISSUE TITLE
erros

### ISSUE THREAD

**Issue by seikichin** [ducdetronquito/scalpl#30]
a.b="text"
can't make
a.b.c="text"

**Comment by ducdetronquito** [comment]
Hello,

I don't understand what you are trying to do.
Could you provide a valid python script that uses scalpl so that I can help you ?

**Comment by seikichin** [comment]
from scalpl import Cut



data = { }

proxy = Cut(data)

proxy.setdefault('a.b.c.d', 40)

print(data)

#{'a': {'b': {'c': {'d': 40}}}}

proxy['a.b.c']=40

#{'a': {'b': {'c': 40}}}

proxy['a.b']=40

#{'a': {'b': 40}}

proxy['a.b.c.d']=40

#this will not works

print(data)

**Comment by seikichin** [comment]
thanks for reply

**Comment by ducdetronquito** [comment]
It does not work, but it is expected: you try to set a value to a nested key that does not exist.
It naturally raises the following exception:

```python
from scalpl import Cut

proxy = Cut({"a": {"b": 40}})
proxy["a.b.c.d"] = 40

> TypeError: Cannot access key 'c' in path 'a.b.c.d': the element must be a dictionary or a list but is of type '<class 'int'>'.
```

Instead you should replace "a.b" key to a dictionary and use `setdefault` which insert missing keys on the fly with a dictionary for value.

```python
proxy = Cut({"a": {"b": 40}})
proxy["a.b"] = {}
proxy.setdefault("a.b.c.d", 40)
```

Currently using `setdefault` to override an existing key does not work, but I don't know if it should: I need to think about it.

```python
proxy = Cut({"a": {"b": 40}})
proxy.setdefault("a.b.c.d", 40)

> TypeError: 'int' object is not subscriptable
```

**Comment by seikichin** [comment]
thanks to you
