### ISSUE TITLE
Is it possible to init Cut from list of dicts

### ISSUE THREAD

**Issue by tnusraddinov** [ducdetronquito/scalpl#7]
Is it possible init Cut from list of dicts:

```
data = [
    { 'name': { 'first': 'A' } },
    { 'name': { 'first': 'B' } },
]

proxy = Cut(data)
proxy['[0].name.first']  # ?
```

**Comment by ducdetronquito** [comment]
Hi @tnusraddinov !

It is currently not possible, but I will try my best to release a new version of Scalpl in the upcoming days to handle this case.

Have a good day :)

**Comment by tnusraddinov** [comment]
Thanks :)

**Comment by ducdetronquito** [comment]
Hi again @tnusraddinov !

After some research, allowing `Cut` to be able to proxy a `list` would actually change the overall purpose of the library as a wrapper for python's dictionnaries.

Besides, most of `Cut` methods like `update`, `all`, `fromkeys`, etc... do not have meanings when proxying a list.

As a conclusion, I will not make it possible to use Scalpl to wrap list as is.

But, you can still handle your use-case with Scalpl, and here is 2 solutions

**1. Wrap your list inside a dictionnary:**

```python3
data = [
    {"name": {"first": "A"}},
    {"name": {"first": "B"}},
]
proxy = Cut({"data": data})
proxy["data[0].name.first"]
```

**2. Proxy each dictionnary individually :**

```python3
data = [
    {"name": {"first": "A"}},
    {"name": {"first": "B"}},
]

proxies = [Cut(item) for item in data]
proxies[0]["name.first"]
```

I would personnally go with the first solution as it is easier to understand 👌

**Comment by tnusraddinov** [comment]
Thanks :+1:

**Comment by ducdetronquito** [comment]
Just a small oversight from me, but the second method to proxy a list of dicts can also be done by using the `Cut.all` method (*which returns a generator*).

```python
items = [
    {"name": {"first": "A"}},
    {"name": {"first": "B"}},
]

for proxy in Cut.all(items):
    print(proxy["name.first"])
```
